apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: playground
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World</title>
    </head>
    <body>
    <h1>Hello World!</h1>
    <p>This is running in Kubernetes</p>
    </body>
    </html>